name: Unit Tests

on:
  push:
    branches: [ main ]  # or 'master' if that's your primary branch name
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

  frontend-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test
